export const advanceEngineAbi = [
  {
    type: "function",
    name: "quote",
    stateMutability: "view",
    inputs: [{ name: "invoiceId", type: "uint256" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "eligible", type: "bool" },
          { name: "maxAdvance", type: "uint256" },
          { name: "feeForMax", type: "uint256" },
          { name: "advanceRateBps", type: "uint16" },
          { name: "feePer30dBps", type: "uint16" },
          { name: "recourseBps", type: "uint16" },
          { name: "tenorDays", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "feeFor",
    stateMutability: "pure",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "feePer30dBps", type: "uint256" },
      { name: "tenor", type: "uint256" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "recourseRequired",
    stateMutability: "pure",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "recourseBps", type: "uint16" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "requestAdvance",
    stateMutability: "payable",
    inputs: [
      { name: "invoiceId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "maxFee", type: "uint256" },
      { name: "recourseMUSD", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getAdvance",
    stateMutability: "view",
    inputs: [{ name: "invoiceId", type: "uint256" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "borrower", type: "address" },
          { name: "payer", type: "address" },
          { name: "principal", type: "uint128" },
          { name: "fee", type: "uint128" },
          { name: "seniorPrincipalDue", type: "uint128" },
          { name: "juniorPrincipalDue", type: "uint128" },
          { name: "seniorFeeDue", type: "uint128" },
          { name: "juniorFeeDue", type: "uint128" },
          { name: "protocolFeeDue", type: "uint128" },
          { name: "recourseMUSD", type: "uint128" },
          { name: "recourseBTC", type: "uint128" },
          { name: "seniorLoss", type: "uint128" },
          { name: "juniorLoss", type: "uint128" },
          { name: "fundedAt", type: "uint64" },
          { name: "advanceRateBps", type: "uint16" },
          { name: "feePer30dBps", type: "uint16" },
          { name: "active", type: "bool" },
          { name: "defaulted", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "hasActiveAdvance",
    stateMutability: "view",
    inputs: [{ name: "invoiceId", type: "uint256" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "vaultDue",
    stateMutability: "view",
    inputs: [{ name: "invoiceId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
] as const;
