export const invoiceRegistryAbi = [
  {
    type: "event",
    name: "InvoiceCreated",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "issuer", type: "address", indexed: true },
      { name: "payer", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "dueDate", type: "uint64", indexed: false },
      { name: "commitment", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "function",
    name: "createInvoice",
    stateMutability: "nonpayable",
    inputs: [
      { name: "payer", type: "address" },
      { name: "commitment", type: "bytes32" },
      { name: "amount", type: "uint128" },
      { name: "dueDate", type: "uint64" },
    ],
    outputs: [{ name: "id", type: "uint256" }],
  },
  {
    type: "function",
    name: "getInvoice",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "issuer", type: "address" },
          { name: "payer", type: "address" },
          { name: "commitment", type: "bytes32" },
          { name: "amount", type: "uint128" },
          { name: "paid", type: "uint128" },
          { name: "issuedAt", type: "uint64" },
          { name: "dueDate", type: "uint64" },
          { name: "acceptedAt", type: "uint64" },
          { name: "closedAt", type: "uint64" },
          { name: "status", type: "uint8" },
          { name: "statusBeforeDispute", type: "uint8" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "amountOwed",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "lateFee",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "acceptanceDigest",
    stateMutability: "view",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "payer", type: "address" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "acceptInvoice",
    stateMutability: "nonpayable",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "openDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "reasonHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "receivableNFT",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
] as const;
